package services

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

type NginxData struct {
	Domain string
	Type   string
	Port   string
}

func GenerateNginxConfig(domain string, typeSite string, port string) (string, error) {
	// === 1. DEFINISI PATH ===
	projectRoot := fmt.Sprintf("/var/www/%s", domain)
	webRoot := filepath.Join(projectRoot, "public_html")
	logsDir := filepath.Join(projectRoot, "logs")
	privateDir := filepath.Join(projectRoot, "private")

	availablePath := fmt.Sprintf("/etc/nginx/sites-available/%s.conf", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/%s.conf", domain)

	// === 2. BUAT STRUKTUR FOLDER ===
	// Buat folder project lengkap
	if err := os.MkdirAll(webRoot, 0755); err != nil {
		return "", fmt.Errorf("gagal buat folder: %v", err)
	}
	os.MkdirAll(logsDir, 0755)
	os.MkdirAll(privateDir, 0755)

	// === 3. GENERATE KONTEN AWAL (HTML vs NODE.JS) ===
	if typeSite == "proxy" {
		// A. Tentukan lokasi app.js
		appPath := filepath.Join(projectRoot, "app.js")

		// B. Buat file app.js (Template Hello World)
		appContent := fmt.Sprintf(`const http = require('http');
const hostname = '127.0.0.1';
const port = %s;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/html');
  res.end('<h1>Hello from Node.js! 🚀</h1><p>Domain: %s</p><p>Port: %s</p>');
});

server.listen(port, hostname, () => {
  console.log('Server running at http://' + hostname + ':' + port + '/');
});`, port, domain, port)

		os.WriteFile(appPath, []byte(appContent), 0644)

		// C. Buat Readme
		readme := fmt.Sprintf("App ini dijalankan otomatis oleh PM2.\nID Process: %s\nPort: %s", domain, port)
		os.WriteFile(filepath.Join(projectRoot, "README.txt"), []byte(readme), 0644)

		// === [LOGIC BARU: AUTO START PM2] ===
		// 1. Hapus dulu process lama (kalau ada) biar gak duplikat/error
		// Kita ignore errornya (karena kalau baru bikin, pasti error "process not found", itu wajar)
		exec.Command("pm2", "delete", domain).Run()

		// 2. Jalankan App Baru
		// Command: pm2 start /var/www/domain.com/app.js --name domain.com
		cmdStart := exec.Command("pm2", "start", appPath, "--name", domain)
		if err := cmdStart.Run(); err != nil {
			// Kalau gagal start PM2, catat error tapi jangan gagalkan create website
			fmt.Println("Gagal start PM2:", err)
		}

		// 3. Simpan state PM2 (Biar kalau VPS restart, app nyala sendiri)
		exec.Command("pm2", "save").Run()

	} else {
		// === LOGIC LAMA: Jika Static/PHP, buatkan index.html ===
		cwd, _ := os.Getwd()
		indexTplPath := filepath.Join(cwd, "templates", "default_index.html")
		indexParams := NginxData{Domain: domain}

		indexTpl, err := template.ParseFiles(indexTplPath)
		if err != nil {
			fallbackContent := fmt.Sprintf("<h1>Welcome to %s</h1><p>Generated by GoPanel</p>", domain)
			os.WriteFile(filepath.Join(webRoot, "index.html"), []byte(fallbackContent), 0644)
		} else {
			indexFile, errCreate := os.Create(filepath.Join(webRoot, "index.html"))
			if errCreate == nil {
				indexTpl.Execute(indexFile, indexParams)
				indexFile.Close()
			}
		}
	}

	// === 4. UPDATE PERMISSION ===
	// Pastikan www-data (Ubuntu) atau nginx (AlmaLinux) bisa akses
	cmdChown := exec.Command("chown", "-R", "nginx:nginx", projectRoot)
	if err := cmdChown.Run(); err != nil {
		exec.Command("chown", "-R", "www-data:www-data", projectRoot).Run()
	}

	// === 5. GENERATE CONFIG NGINX ===
	cwd, _ := os.Getwd()
	tplPath := filepath.Join(cwd, "templates", "nginx_site.tpl")

	tpl, err := template.ParseFiles(tplPath)
	if err != nil {
		return "", fmt.Errorf("gagal baca template nginx: %v", err)
	}

	file, err := os.Create(availablePath)
	if err != nil {
		return "", fmt.Errorf("gagal tulis config: %v", err)
	}

	data := NginxData{Domain: domain, Type: typeSite, Port: port}
	err = tpl.Execute(file, data)
	file.Close()
	if err != nil {
		return "", fmt.Errorf("gagal eksekusi template: %v", err)
	}

	// === 6. RESTART NGINX ===
	os.Remove(enabledPath)
	os.Symlink(availablePath, enabledPath)

	cmd := exec.Command("systemctl", "restart", "nginx")
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("gagal restart nginx: %v", err)
	}

	return availablePath, nil
}

func RemoveNginxConfig(domain string) error {
	// Definisikan path yang mau dihapus
	projectRoot := fmt.Sprintf("/var/www/%s", domain) // Hapus folder induknya
	availablePath := fmt.Sprintf("/etc/nginx/sites-available/%s.conf", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/%s.conf", domain)

	// 1. Hapus Config Nginx
	os.Remove(enabledPath)
	os.Remove(availablePath)

	// 2. Hapus Folder Project (Termasuk public_html, logs, private)
	// Hati-hati, ini menghapus permanen!
	if err := os.RemoveAll(projectRoot); err != nil {
		return fmt.Errorf("gagal hapus folder project: %v", err)
	}

	// 3. Restart Nginx
	cmd := exec.Command("systemctl", "restart", "nginx")
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("gagal restart nginx: %v", err)
	}

	return nil
}
