package services

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings" // <--- PENTING: Untuk split command
	"text/template"
)

type NginxData struct {
	Domain string
	Type   string
	Port   string
}

// Update parameter: tambah startCmd
func GenerateNginxConfig(domain string, typeSite string, port string, startCmd string) (string, error) {
	// === 1. DEFINISI PATH (STRUKTUR HYBRID) ===

	// Folder Project (Wadah Utama) -> /var/www/domain.com
	projectRoot := fmt.Sprintf("/var/www/%s", domain)

	// Folder Public (Web Root) -> /var/www/domain.com/public_html
	webRoot := filepath.Join(projectRoot, "public_html")

	// Folder Logs & Private
	logsDir := filepath.Join(projectRoot, "logs")
	privateDir := filepath.Join(projectRoot, "private")

	// Lokasi Config Nginx
	availablePath := fmt.Sprintf("/etc/nginx/sites-available/%s.conf", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/%s.conf", domain)

	// === 2. BUAT STRUKTUR FOLDER ===
	// Kita buat folder public_html (ini otomatis membuat folder projectRoot juga)
	if err := os.MkdirAll(webRoot, 0755); err != nil {
		return "", fmt.Errorf("gagal buat folder webroot: %v", err)
	}
	// Buat folder logs & private
	os.MkdirAll(logsDir, 0755)
	os.MkdirAll(privateDir, 0755)

	// === 3. GENERATE KONTEN AWAL ===
	if typeSite == "proxy" {
		// === LOGIC PROXY (NODE.JS / PYTHON / NEXT.JS) ===

		// A. Generate Dummy App (Hanya jika belum ada app.js)
		appPath := filepath.Join(projectRoot, "app.js")
		if _, err := os.Stat(appPath); os.IsNotExist(err) {
			appContent := fmt.Sprintf(`const http = require('http');
const hostname = '127.0.0.1';
const port = %s;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/html');
  res.end('<h1>Hello from Node.js! 🚀</h1><p>Domain: %s</p><p>Port: %s</p>');
});

server.listen(port, hostname, () => {
  console.log('Server running at http://' + hostname + ':' + port + '/');
});`, port, domain, port)
			os.WriteFile(appPath, []byte(appContent), 0644)
		}

		// B. GENERATE ECOSYSTEM.CONFIG.JS (Untuk PM2)
		// Kita pecah startCmd. Contoh: "npm run start" -> Script: "npm", Args: "run start"
		parts := strings.SplitN(startCmd, " ", 2)
		script := parts[0]
		args := ""
		if len(parts) > 1 {
			args = parts[1]
		}

		// Template Ecosystem File
		ecosystemContent := fmt.Sprintf(`module.exports = {
  apps : [{
    name   : "%s",
    script : "%s",
    args   : "%s",
    cwd    : "/var/www/%s",
    env: {
       PORT: %s,
       NODE_ENV: "production"
    }
  }]
}`, domain, script, args, domain, port)

		// Tulis file ecosystem
		os.WriteFile(filepath.Join(projectRoot, "ecosystem.config.js"), []byte(ecosystemContent), 0644)

		// C. JALANKAN PM2
		// Hapus process lama biar gak duplikat
		exec.Command("pm2", "delete", domain).Run()

		// Start pakai ecosystem config
		cmdStart := exec.Command("pm2", "start", filepath.Join(projectRoot, "ecosystem.config.js"))
		if err := cmdStart.Run(); err != nil {
			fmt.Println("⚠️ Gagal start PM2 (Mungkin belum install?):", err)
		}
		// Simpan state PM2
		exec.Command("pm2", "save").Run()

	} else {
		// === LOGIC STATIC / PHP ===
		// Generate index.html dari template
		cwd, _ := os.Getwd()
		indexTplPath := filepath.Join(cwd, "templates", "default_index.html")
		indexParams := NginxData{Domain: domain}

		// Cek Template
		indexTpl, err := template.ParseFiles(indexTplPath)
		if err != nil {
			fallbackContent := fmt.Sprintf("<h1>Welcome to %s</h1><p>Generated by GoPanel</p>", domain)
			os.WriteFile(filepath.Join(webRoot, "index.html"), []byte(fallbackContent), 0644)
		} else {
			indexFile, errCreate := os.Create(filepath.Join(webRoot, "index.html"))
			if errCreate == nil {
				indexTpl.Execute(indexFile, indexParams)
				indexFile.Close()
			}
		}
	}

	// === 4. UPDATE PERMISSION (CHOWN) ===
	cmdChown := exec.Command("chown", "-R", "nginx:nginx", projectRoot)
	if err := cmdChown.Run(); err != nil {
		// Fallback for Ubuntu/Debian
		exec.Command("chown", "-R", "www-data:www-data", projectRoot).Run()
	}

	// === 5. GENERATE CONFIG NGINX ===
	cwd, _ := os.Getwd()
	tplPath := filepath.Join(cwd, "templates", "nginx_site.tpl")
	tpl, err := template.ParseFiles(tplPath)
	if err != nil {
		return "", fmt.Errorf("gagal baca template nginx: %v", err)
	}

	file, err := os.Create(availablePath)
	if err != nil {
		return "", fmt.Errorf("gagal tulis config: %v", err)
	}

	data := NginxData{Domain: domain, Type: typeSite, Port: port}
	err = tpl.Execute(file, data)
	file.Close()
	if err != nil {
		return "", fmt.Errorf("gagal eksekusi template config: %v", err)
	}

	// === 6. SYMLINK & RELOAD ===
	os.Remove(enabledPath)
	if err := os.Symlink(availablePath, enabledPath); err != nil {
		return "", fmt.Errorf("gagal symlink: %v", err)
	}

	// Gunakan Restart agar bersih
	cmd := exec.Command("systemctl", "restart", "nginx")
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("gagal restart nginx: %v", err)
	}

	return availablePath, nil
}

func RemoveNginxConfig(domain string) error {
	projectRoot := fmt.Sprintf("/var/www/%s", domain)
	availablePath := fmt.Sprintf("/etc/nginx/sites-available/%s.conf", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/%s.conf", domain)

	// 1. Matikan PM2 (Jika ada process-nya)
	// Kita jalankan saja command delete, kalau error (karena gak ada process) biarin aja.
	exec.Command("pm2", "delete", domain).Run()
	exec.Command("pm2", "save").Run()

	// 2. Hapus Config Nginx
	os.Remove(enabledPath)
	os.Remove(availablePath)

	// 3. Hapus Folder Project
	if err := os.RemoveAll(projectRoot); err != nil {
		return fmt.Errorf("gagal hapus folder project: %v", err)
	}

	// 4. Restart Nginx
	cmd := exec.Command("systemctl", "restart", "nginx")
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("gagal restart nginx: %v", err)
	}

	return nil
}
