package services

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"text/template"
)

type NginxData struct {
	Domain string
	Type   string
	Port   string
}

func GenerateNginxConfig(domain string, typeSite string, port string) (string, error) {
	// === 1. DEFINISI PATH (STRUKTUR HYBRID) ===

	// Folder Project (Wadah Utama) -> /var/www/domain.com
	projectRoot := fmt.Sprintf("/var/www/%s", domain)

	// Folder Public (Web Root) -> /var/www/domain.com/public_html
	webRoot := filepath.Join(projectRoot, "public_html")

	// Folder Logs & Private
	logsDir := filepath.Join(projectRoot, "logs")
	privateDir := filepath.Join(projectRoot, "private")

	// Lokasi Config Nginx
	availablePath := fmt.Sprintf("/etc/nginx/sites-available/%s.conf", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/%s.conf", domain)

	// === 2. BUAT STRUKTUR FOLDER ===
	// Kita buat folder public_html (ini otomatis membuat folder projectRoot juga)
	if err := os.MkdirAll(webRoot, 0755); err != nil {
		return "", fmt.Errorf("gagal buat folder webroot: %v", err)
	}
	// Buat folder logs & private
	os.MkdirAll(logsDir, 0755)
	os.MkdirAll(privateDir, 0755)

	// === 3. GENERATE INDEX.HTML (Di dalam public_html) ===
	cwd, _ := os.Getwd()
	indexTplPath := filepath.Join(cwd, "templates", "default_index.html")
	indexParams := NginxData{Domain: domain}

	// Cek Template
	indexTpl, err := template.ParseFiles(indexTplPath)
	if err != nil {
		// Fallback jika template hilang
		fallbackContent := fmt.Sprintf("<h1>Welcome to %s</h1><p>Generated by GoPanel</p>", domain)
		os.WriteFile(filepath.Join(webRoot, "index.html"), []byte(fallbackContent), 0644)
	} else {
		// Generate dari Template
		indexFile, errCreate := os.Create(filepath.Join(webRoot, "index.html"))
		if errCreate == nil {
			indexTpl.Execute(indexFile, indexParams)
			indexFile.Close()
		}
	}

	// === 4. UPDATE PERMISSION (CHOWN) ===
	// Kita ubah kepemilikan SATU FOLDER PROJECT (Recursive) agar user nginx bisa akses semuanya
	// Ganti 'nginx:nginx' jadi 'www-data:www-data' jika pakai Ubuntu
	cmdChown := exec.Command("chown", "-R", "nginx:nginx", projectRoot)
	if err := cmdChown.Run(); err != nil {
		// Fallback for Ubuntu/Debian
		exec.Command("chown", "-R", "www-data:www-data", projectRoot).Run()
	}

	// === 5. GENERATE CONFIG NGINX ===
	// Pastikan template Nginx kamu (nginx_site.tpl) root-nya mengarah ke:
	// root /var/www/{{ .Domain }}/public_html;

	tplPath := filepath.Join(cwd, "templates", "nginx_site.tpl")
	tpl, err := template.ParseFiles(tplPath)
	if err != nil {
		return "", fmt.Errorf("gagal baca template nginx: %v", err)
	}

	file, err := os.Create(availablePath)
	if err != nil {
		return "", fmt.Errorf("gagal tulis config: %v", err)
	}

	data := NginxData{Domain: domain, Type: typeSite, Port: port}
	err = tpl.Execute(file, data)
	file.Close()
	if err != nil {
		return "", fmt.Errorf("gagal eksekusi template config: %v", err)
	}

	// === 6. SYMLINK & RELOAD ===
	os.Remove(enabledPath)
	if err := os.Symlink(availablePath, enabledPath); err != nil {
		return "", fmt.Errorf("gagal symlink: %v", err)
	}

	// Gunakan Restart agar bersih
	cmd := exec.Command("systemctl", "restart", "nginx")
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("gagal restart nginx: %v", err)
	}

	return availablePath, nil
}

func RemoveNginxConfig(domain string) error {
	// Definisikan path yang mau dihapus
	projectRoot := fmt.Sprintf("/var/www/%s", domain) // Hapus folder induknya
	availablePath := fmt.Sprintf("/etc/nginx/sites-available/%s.conf", domain)
	enabledPath := fmt.Sprintf("/etc/nginx/sites-enabled/%s.conf", domain)

	// 1. Hapus Config Nginx
	os.Remove(enabledPath)
	os.Remove(availablePath)

	// 2. Hapus Folder Project (Termasuk public_html, logs, private)
	// Hati-hati, ini menghapus permanen!
	if err := os.RemoveAll(projectRoot); err != nil {
		return fmt.Errorf("gagal hapus folder project: %v", err)
	}

	// 3. Restart Nginx
	cmd := exec.Command("systemctl", "restart", "nginx")
	if err := cmd.Run(); err != nil {
		return fmt.Errorf("gagal restart nginx: %v", err)
	}

	return nil
}
